# Generated by Django 4.2.1 on 2023-05-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matchday", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="last_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name="author",
            index=models.Index(
                fields=["last_name", "first_name"],
                name="matchday_au_last_na_b06304_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(
                fields=["author"], name="matchday_qu_author__19451c_idx"
            ),
        ),
    ]
